# http://goreleaser.com
project_name: rubbi-sh
before:
  hooks:
    - go mod download
    - ./tools/bump-version.sh
    - ./tools/tag-version.sh
builds:
- env:
  - CGO_ENABLED=0
archives:
  -
    id: default
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md
      - dotfiles/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .FullCommit }}-{{ .Tag }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
