# http://goreleaser.com
project_name: rubbi-sh
before:
  hooks:
    - go mod download
    - ./tools/bump-version.sh
    - ./tools/tag-version.sh
builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
