# http://goreleaser.com
project_name: rubbi-sh
before:
  hooks:
    - go mod download
    - ./tools/bump-version.sh
    - ./tools/tag-version.sh
builds:
- env:
  - CGO_ENABLED=0
archives:
  -
    id: default
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md
      - install.sh
      - dotfiles/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .FullCommit }}-{{ .Tag }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
sign:
  signature: "${artifact}.sig"
  cmd: gpg
  args: ["-u", "josriolop@gmail.com", "--output", "${signature}", "--detach-sign", "${artifact}"]
  artifacts: all
