# http://goreleaser.com
project_name: rubbi-sh
before:
  hooks:
    - go mod download
    - ./tools/bump-version.sh
    - ./tools/tag-version.sh
builds:
- env:
  - CGO_ENABLED=0
archives:
  -
    id: default
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md
      - install.sh
      - dotfiles/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .FullCommit }}-{{ .Tag }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
sign:
  # name of the signature file.
  # '${artifact}' is the path to the artifact that should be signed.
  #
  signature: "${artifact}.sig"

  # path to the signature command
  #
  cmd: gpg

  # command line arguments for the command
  #
  # to sign with a specific key use
  args: ["-u", "josriolop@gmail.com", "--output", "${signature}", "--detach-sign", "${artifact}"]
  #
  # args: ["--output", "${signature}", "--detach-sign", "${artifact}"]


  # which artifacts to sign
  #
  #   checksum: only checksum file(s)
  #   all:      all artifacts
  #   none:     no signing
  #
  artifacts: all
