# http://goreleaser.com
project_name: rubbi-sh
before:
  hooks:
  - go mod download
  # So far, we better do this manually
  # - ./tools/bump-version.sh
  # - ./tools/tag-version.sh
builds:
- goarch:
  - amd64
archives:
- id: default
  files:
    - CHANGELOG.md
    - LICENSE
    - README.md
    - install.sh
    - dotfiles/*
  replacements:
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .FullCommit }}-{{ .Tag }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
signs:
- id: deafult
  artifacts: all
  signature: "${artifact}.sig"
  cmd: gpg
  args:
    - "--batch"
    - "--local-user"
    - "{{ .Env.GPG_FINGERPRINT }}"
    - "--output"
    - "${signature}"
    - "--detach-sign"
    - "${artifact}"

# Homebrew formula
brews:
- name: rubbi-sh
  homepage: https://github.com/jotadrilo/rubbi-sh
  description: Go and Shell helpers to provide a sandbox directory for rubbish.
  url_template: "https://github.com/jotadrilo/rubbi-sh/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  tap:
    owner: jotadrilo
    name: homebrew-tap
  folder: formula
  commit_author:
    name: jotadrilo
    email: josriolop@gmail.com
  skip_upload: auto
  ids:
  - default
  install: |
    bin.install "rubbi-sh"
    (share/"alias").install "dotfiles/.rubbi.sh"
    (share/"alias").install "dotfiles/.rubbi.minimal.sh"
  caveats: |
    Please import the .rubbi.sh file in your profile configuration or add its content directly

     . #{(share/"alias")}/.rubbi.sh

    or the .rubbi.minimal.sh for a minimal setup (rbsh shell function only)

     . #{(share/"alias")}/.rubbi.minimal.sh

    This tool is based on some alias and shell functions that are core to work.

  test: |
    system bin/"rubbi-sh", "-version"
